forgot password
ctc-uci/authentication-frontend pull request #15
Opened 2022-02-07 00:38 UTC by ctc-devops

Workflow:
user clicks on forgot password button
user enters in email
our service sends email to user which contains a link to change their password
password is changed :)
closes #8

2022-02-07 21:05 UTC, Vakhshoori101 requested changes
address comments

2022-02-07 21:05 UTC, Vakhshoori101 commented on src/utils/auth_utils.js
> +  }
like we talked about, no need for this try/catch

2022-02-07 21:05 UTC, Vakhshoori101 commented on src/App.jsx
> +          <Route exact path="/forgotpassword" element={<ForgotPassword />} />
sort alphabetically XD

2022-02-08 02:28 UTC, nguyenethan01 commented on src/App.jsx
> +          <Route exact path="/forgotpassword" element={<ForgotPassword />} />
no

2022-02-08 02:44 UTC, merged