user login logout
ctc-uci/authentication-frontend pull request #5
Opened 2022-01-23 01:21 UTC by ctc-devops

Logins Include
- Native Login (Email and Password)
- Google Login

Ref the sprint doc for more information about the workflows: https://docs.google.com/document/d/1T9SyUpl273e6UIen7ZR5ln4d4HsrtLdRBEy9dJf1RQc/edit

closes #3

2022-01-28 00:57 UTC, ctc-devops commented on src/utils/auth_utils.js
> +    console.error(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-01-28 00:57 UTC, ctc-devops commented on src/utils/auth_utils.js
> +    alert(err.message);
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-02-01 20:36 UTC, Vakhshoori101 requested changes
Overall looks really good and all features work as expected, but I've listed few things to fix. See the slack message in for our reasoning.
Try to finish these changes before starting on next sprints work.

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/App.jsx
> +          <Route exact path="/logout" element={<LogoutTest />} />
Please rename these two components to be without the "Test"

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/components/LoginTest.jsx
> +    }
This logic should be moved into the `logInWithEmailAndPassword` function in `auth_utils` so its easier for NPO teams to implement. The redirect path should be a prop passed into the function for the same reason. 
Also add a try/catch around the `logInWithEmailAndPassword` in the case an error was thrown inside of it. In the catch, the error message will be put in the `errorMessage` state which will then be outputted in the JSX.

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/components/LoginTest.jsx
> +  const navigate = useNavigate();
Add a new `errorMessage` state to store/display any errors during account creation. If an error is thrown during `logInWithEmailAndPassword`, it should be rendered on the page.

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/components/LoginTest.jsx
> +        navigate('/');
Similar to previous comment, logic should be moved to `signInWithGoogle`. also add try/catch around `signInWithGoogle`

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/components/LogoutTest.jsx
> +    clearCookies(cookies);
similar to previous comments, `logout` should include a parameter for redirected route after success. also move logic for clearing cookies to `logout` function as well. also add try/catch around `logout`

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/utils/auth_utils.js
> +    return err;
change from returning to throwing the error. also this method will take two redirect paths depending on if user is new or not

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/utils/auth_utils.js
> +    return false;
replace with throw, remove the `return true`. if nothing is thrown, we assume the method call was successful.

2022-02-01 20:36 UTC, Vakhshoori101 commented on src/utils/auth_utils.js
> +  await signOut(auth);
add try/catch

2022-02-02 00:10 UTC, claudeisakeeb commented on src/App.jsx
> +          <Route exact path="/logout" element={<LogoutTest />} />
Renamed to Login and Logout

2022-02-02 00:11 UTC, claudeisakeeb commented on src/components/LoginTest.jsx
> +    }
- Made redirect path and useNavigate instance function parameters
- Added try catch around loginWithEmailAndPassword
- Set errorMessage on error in Login

2022-02-02 00:12 UTC, claudeisakeeb commented on src/components/LoginTest.jsx
> +  const navigate = useNavigate();
Added errorMessage instance and rendering mechanics

2022-02-02 00:12 UTC, claudeisakeeb commented on src/components/LoginTest.jsx
> +        navigate('/');
Moved logic into signInWithGoogle and added try catch around function call

2022-02-02 00:13 UTC, claudeisakeeb commented on src/components/LogoutTest.jsx
> +    clearCookies(cookies);
Added necessary parameters and try catch

2022-02-02 00:14 UTC, claudeisakeeb commented on src/utils/auth_utils.js
> +    return err;
Ended up removing try catch around the code in utils functions

2022-02-02 00:15 UTC, claudeisakeeb commented on src/utils/auth_utils.js
> +    return false;
Ended up removing return statements in utils functions

2022-02-02 00:15 UTC, claudeisakeeb commented on src/utils/auth_utils.js
> +  await signOut(auth);
Added try catch

2022-02-03 02:56 UTC, Vakhshoori101 commented on src/utils/auth_utils.js
> +  await signOut(auth);
yuh you right

2022-02-03 03:00 UTC, Vakhshoori101 approved these changes
LGTM

2022-02-03 03:00 UTC, merged